version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge